sudo: required
services:
  - docker
before_install:
  - docker pull php:7.2-fpm-alpine3.6
  - echo $DOCKER_PWD | docker login $DOCKER_REG -u $DOCKER_USER --password-stdin

script:
  - docker build -t $DOCKER_REG/0x01301c74/php-fpm-slim .

after_success:
  - docker push $DOCKER_REG/0x01301c74/php-fpm-slim