sudo: required
services:
  - docker
before_install:
  - docker pull php:7.2-fpm-alpine3.6
  - echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin

script:
  - docker build -t cjy632258/php-fpm-slim .
  - docker build -t cjy632258/php-cli -f cli/Dockerfile .
  - docker build -t cjy632258/php-fpm-slim:nginx -f nginx/Dockerfile .

after_success:
  - docker push cjy632258/php-fpm-slim
  - docker push cjy632258/php-fpm-slim:nginx
  - docker push cjy632258/php-cli